# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUploadfile():
  def setup_method(self, method):
    #self.driver = webdriver.Firefox()
    service = Service(r"C:\Drivers\geckodriver.exe")
    self.driver = webdriver.Firefox(service=service)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uploadfile(self):
    self.driver.get("https://demoqa.com/automation-practice-form")
    self.driver.set_window_size(925, 765)
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Anahi")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Quezada")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("anahi@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-radio:nth-child(2) > .custom-control-label").click()
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.ID, "userNumber").send_keys("0000000000")
    self.driver.find_element(By.ID, "dateOfBirthInput").click()
    self.driver.find_element(By.CSS_SELECTOR, ".subjects-auto-complete__value-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(3) > .custom-control-label").click()
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").send_keys("direccion")
    self.driver.find_element(By.ID, "uploadPicture").click()
    self.driver.find_element(By.ID, "uploadPicture").send_keys("C:\\Users\\Usuario\\Pictures\\efa9a9ee91943bbc341a2ef99df55a14.jpg")
    self.driver.find_element(By.ID, "submit").click()
    element = self.driver.find_element(By.ID, "submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "#fixedban div:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#fixedban div:nth-child(4)").click()
  
